// ! Made by rishit khandelwal (github.com/rishit-khandelwal)
import Head from "next/head";
import InfoBox from "@/components/InfoBox";
import Layout from "@/components/Layout";
import Sparkles from "@/components/Sparkles/Sparkles";
import { motion } from "framer-motion";
import styled from "styled-components";

const Body = () => {
  const fadeIn = {
    hidden: {
      scale: 0.5,
      opacity: 0,
    },
    visible: {
      scale: 1,
      opacity: 1,
      transition: {
        delay: 0.5,
      },
    },
  };
  return (
    <div>
      <motion.div
        initial="hidden"
        animate="visible"
        variants={{
          hidden: {
            opacity: 0,
            x: -100,
          },
          visible: {
            opacity: 1,
            x: 0,
            transition: {
              delay: 0.5,
            },
          },
        }}
      >
        <InfoBox title={"Go Back"} linkUrl={"/"} />
      </motion.div>
      <motion.div initial="hidden" animate="visible" variants={fadeIn}>
        <Sparkles>
          <Title>Instructions</Title>
        </Sparkles>
      </motion.div>
      <motion.div initial="hidden" animate="visible" variants={fadeIn}>
        <Description>
          <UnorderedList>
            <li>Click on play button to start the quiz</li>
            <li>Select any state or UT of your choice</li>
            <li>Click on Go!</li>
            <li>Choose a state</li>
            <li>Attempt the quiz</li>
            <li>
              Also there is a timer, so after 30 seconds it will move to next
              question
            </li>
            <li>
              After completion of each state quiz, the score will be added and
              total score will be displayed
            </li>
            <li>
              Clicking on the button on the top left corner will switch the
              language to hindi from english and vice versa
            </li>
            <li>
              For questions with images, a link is displayed above the question,
              clicking on which will open the image
            </li>
          </UnorderedList>
        </Description>
      </motion.div>
    </div>
  );
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vividham Sanskritam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout body={<Body />} />
      </main>
    </div>
  );
}

const Title = styled.h1`
  line-height: 2.5rem;
  font-size: 2rem;
  font-weight: 600;
  text-align: center;
`;

const Description = styled.span`
  color: var(--primary-grey);
  text-align: center;
  font-weight: 600;
`;

const UnorderedList = styled.ul`
  list-style: none;
`;
